/*
 * Colby King
 * Programming Assignment 1
 * CS2300
 * Due Feb 12, 2023
 * 
 * 
 * PART 1
 */

import java.io.File;
import java.io.PrintWriter;

public class cking_p1 {

	public static void main(String[] args) {
		// Part 1: Write Program using array that generates and write out
		// five matrices defined below. Must be generated by program and
		// not hard coded

		// Mat 1:
		// Number of rows = number of letters in your first name
		// Number of columns = number of letters in you last name
		Matrix m1 = new Matrix(5,4);
		m1.fillMatrix(1, 1, false);
		m1.display();
		m1.printToFile("cking_mat1.txt");

		
		Matrix m2 = new Matrix(4, 5);
		m2.fillMatrix(4, 2, false);
		m2.display();
		m2.printToFile("cking_mat2.txt");
		
		
		Matrix m3 = new Matrix(4, 5);
		m3.fillMatrix(0.3, 0.1, true);
		m3.display();
		m3.printToFile("cking_mat3.txt");
		
		Matrix m4 = new Matrix(9, 11);
		m4.fillMatrix(3, 3, false);
		m4.display();
		m4.printToFile("cking_mat4.txt");
		
		Matrix m5 = new Matrix(9, 11);
		m5.fillMatrix(-5, 1.5, true);
		m5.display();
		m5.printToFile("cking_mat5.txt");
		

	}// Main

}// Class

class Matrix {
	double[][] contents;

	public Matrix(int rows, int columns) {
		contents = new double[rows][columns];
	}

	public void fillMatrix(double startingValue, double incrementer, boolean rowsFirst) {
		double value = startingValue;

		if (rowsFirst) {
			for (int i = 0; i < contents[0].length; i++) {
				for (int j = 0; j < contents.length; j++) {
					contents[j][i] = value;
					value += incrementer;
				}
			}
		}

		else {
			for (int i = 0; i < contents.length; i++) {
				for (int j = 0; j < contents[0].length; j++) {
					contents[i][j] = value;
					value += incrementer;
				}
			}

		}
	}

	public void display() {
		for (int i = 0; i < contents.length; i++) {
			for (int j = 0; j < contents[i].length; j++) {
				System.out.print(contents[i][j] + " ");

			}
			System.out.println();
		}
	}

	public void printToFile(String filename) {
		try {
			PrintWriter writer = new PrintWriter(new File(filename));

			for (int i = 0; i < contents.length; i++) {
				for (int j = 0; j < contents[i].length; j++) {
					writer.printf("%.1f ", contents[i][j], " ");

				}
				writer.println();
			}
			writer.close();

		}

		catch (Exception e) {
			e.printStackTrace();
		}

	}

}// Matrix



